### ISSUE TITLE
Could not open socket to "gateway.discord.gg:443"

### ISSUE THREAD

**Issue by ricardoboss** [laravel-notification-channels/discord#24]
I tried running `php artisan discord:setup` and got this output:

```

 Is the bot already added to your server? (yes/no) [no]:
 >

 What is your Discord app client ID?:
 > <client_id>

Add the bot to your server by visiting this link: https://discordapp.com/oauth2/authorize?&client_id=<client_id>&scope=bot&permissions=0

 Continue? (yes/no) [yes]:
 >

Attempting to identify the bot with Discord's websocket gateway...
Could not get a websocket gateway address, defaulting to 'wss://gateway.discord.gg'.
Connecting to 'wss://gateway.discord.gg'...

   WebSocket\ConnectionException  : Could not open socket to "gateway.discord.gg:443":  (0).

  at S:\repos\totoro\vendor\textalk\websocket\lib\Client.php:60
    56|     // Open the socket.  @ is there to supress warning that we will catch in check below instead.
    57|     $this->socket = @fsockopen($host_uri, $port, $errno, $errstr, $this->options['timeout']);
    58| 
    59|     if ($this->socket === false) {
  > 60|       throw new ConnectionException(
    61|         "Could not open socket to \"$host:$port\": $errstr ($errno)."
    62|       );
    63|     }
    64| 

  Exception trace:

  1   WebSocket\Client::connect()
      S:\repos\totoro\vendor\textalk\websocket\lib\Base.php:30

  2   WebSocket\Base::send("{"op":2,"d":{"token":"<bot api token>","v":3,"compress":false,"properties":{"$os":"WINNT","$browser":"laravel-notification-channels-discord","$device":"laravel-notification-channels-discord","$
referrer":"","$referring_domain":""}}}")
      S:\repos\totoro\vendor\laravel-notification-channels\discord\src\Commands\SetupCommand.php:96

  Please use the argument -v to see more details.
```

Could this happen because the gateway version is too old? I had a quick look at the discord dev portal and saw the latest version is 6, not 3 as used in the request.

**Comment by ricardoboss** [comment]
Turns out if `fsockopen` fails by returning false AND the `errno` is 0, it means something went wrong while creating the socket, before connect is even called.

I can't say if it has to do with my environment or not? Are there any special dependencies? Does this work on Windows?

**Comment by codyphobe** [comment]
Just tagged [v1.0.7](https://github.com/laravel-notification-channels/discord/releases/tag/v1.0.7) which should fix this issue.

**Comment by ricardoboss** [comment]
I updated to the latest version but the same error still occurs.

Maybe you should update the `textalk\websocket` dependency to `^1.2`. They made changes on the socket creation and fixed a few issues. I'll create a pull request and look for errors for you.

**Comment by ricardoboss** [comment]
Okay so after doing some local tests I found out that executing the command in WSL (Ubuntu) works perfectly fine. This problem seems to be **Windows specific**.

Anyway I still updated and tested the `textalk/websocket` dependency. Related MR: #25

**Comment by codyphobe** [comment]
Interesting. It may be worth switching to another library to handle the websocket connection, the main reason I chose `textalk/websocket` was because of how small it is since it's only needed during the initial setup. I'll start looking into alternative websocket libraries and I'll leave this issue open in the meantime.

**Comment by codyphobe** [comment]
This actually seems to be an issue not specific to `textalk/websocket`, but has been discussed in Textalk/websocket-php#50, and seems a solution would be to disable `verify_peer` and `verify_peer_name` on the context. Possible solution:

```php
// SetupCommand.php

public function getSocket($gateway)
{
    $context = stream_context_create();

    stream_context_set_option($context, 'ssl', 'verify_peer', false);
    stream_context_set_option($context, 'ssl', 'verify_peer_name', false);

    return new Client($gateway, ['context' => $context]);
}
```

**Comment by ricardoboss** [comment]
This seems to have fixed the problem! I suppose we can use the `.env`'s variables to conditionally add those options to the stream context like this:

```php
// SetupCommand.php

public function getSocket($gateway)
{
    $context = stream_context_create();

    if (env('APP_ENV') == "local") {
        stream_context_set_option($context, 'ssl', 'verify_peer', false);
        stream_context_set_option($context, 'ssl', 'verify_peer_name', false);
    }

    return new Client($gateway, ['context' => $context]);
}
```

Another variable which could be used is `APP_DEBUG`.

I could also think of a command option for `discord:setup` to toggle this behaviour. What do you think is best @codyphobe ?

**Comment by ricardoboss** [comment]
Looking at this line:

```
Could not get a websocket gateway address, defaulting to 'wss://gateway.discord.gg'.
```

There is also an error connecting to `https://discordapp.com/api/gateway` using guzzle. The method used for `getSocket()` to disable peer verification could also apply here:

```php
// SetupCommand.php

public function getGateway() {
    ...
    $response = $this->guzzle->get(
        'https://discordapp.com/api/gateway',
        [
            'verify' => env('APP_ENV') != "local"
        ]
    );
    ...
}
```

**Comment by codyphobe** [comment]
In your local environment, after the library has been successfully set up with `discord:setup`, does Guzzle complain about SSL verification with normal use of the library without disabling SSL verification?

I would prefer adding an option on the command with a note in the README and printing a feedback message in the terminal if a `WebSocket\ConnectionException` is thrown without the option present, but if Guzzle also errors out with normal use of the library then maybe a config flag (e.g. `ssl.verify`) that defaults to `true` would be best, that way users can choose to disable SSL verification without modifying their environment.

Either way I think it's necessary to add a footnote in the README about making sure that PHP is configured properly on Windows for users that experience this problem [[1](https://www.saotn.org/dont-turn-off-curlopt_ssl_verifypeer-fix-php-configuration/), [2](https://stackoverflow.com/questions/39687720/ssl-not-work-in-php5-6-on-windows)]

**Comment by ricardoboss** [comment]
No, it does not work:

```
NotificationChannels\Discord\Exceptions\CouldNotSendNotification  : Communication with Discord failed: 0: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

I'd say add an option to the command to disable it once but if users want to use it that way it should still fail. Maybe check if ssl is set up and warn the user to avoid cryptic error messages.

**Comment by ricardoboss** [comment]
Just tried it again and got error 400:
`NotificationChannels\Discord\Exceptions\CouldNotSendNotification  : Discord responded with an HTTP error: 400`

Probably not related to the ssl error but do you know what could have caused this?

**Comment by Felli** [comment]
Out of curiosity, why is baseUrl not requesting `v6`?
https://github.com/laravel-notification-channels/discord/blob/2d3501b1bfd6959019e2c8dbaab0a779905693e9/src/Discord.php#L18

https://github.com/laravel-notification-channels/discord/blob/2d3501b1bfd6959019e2c8dbaab0a779905693e9/src/Discord.php#L82

See [Connecting to the Gateway](https://discordapp.com/developers/docs/topics/gateway#connecting-to-the-gateway) from the Discord Docs.

**Comment by codyphobe** [comment]
The API version isn't specified so that it will default to the latest version.

As for the `400` error, I'm unsure as there are a number of things that can go wrong. A DM could fail because it's too long, the user has blocked the bot, the user has public DMs disabled, the bot account has them disabled, or the message is malformed. It's worth noting that while trying to replicate the `400` error, I could only get a `403` when the user had public DMs disabled.

**Comment by ricardoboss** [comment]
It didn't even get to sending a DM. The error occured while getting the private channel for my username.

At least the ssl error is fixed now. For me, this issue can be closed now. As for the 400 error, I'll look into it tomorrow and open a new issue for it's own discussions if I find anything related to it.

**Comment by codyphobe** [comment]
> The error occured while getting the private channel for my username.

Did you pass a username into `getPrivateChannel`? If so, that method and API route expects the snowflake ID for a user. That's my bad for not being specific in that method's documentation; all it says is "user", I wouldn't expect you to know that it needed an ID without having to look at the source.

I don't see any non-OAuth Discord API for getting a user's id from the username and tag, otherwise I would just add that to the method. The best bet seems to be just asking users to copy & paste their ID manually or allow them to login with Discord and store their ID from the OAuth flow.

**Comment by ricardoboss** [comment]
I used my username in the form of "Mizzle#8643".

**Comment by codyphobe** [comment]
Okay, so that's why it's returning a `400`. You can get your Discord user ID by turning on developer mode in the `Advanced` section of the `Appearance` settings window and then right-clicking your username in the user list of a server and selecting `Copy ID`. I'll go ahead and add some clarification to the README as well as the method documentation on what exactly should be passed in.
